/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import javax.swing.UIManager;

/**
 *
 * @author ILS
 */
public class IUPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form IUPrincipal
     */
    public IUPrincipal() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jBotonRegDoc = new javax.swing.JButton();
        jBotonModDoc = new javax.swing.JButton();
        jBotonElimDoc = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jBotonAsignHora = new javax.swing.JButton();
        jBotonModHora = new javax.swing.JButton();
        jBotonElimHora = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jBotonRegLic = new javax.swing.JButton();
        jBotonModLic = new javax.swing.JButton();
        jBotonElimLic = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jBotonRegRen = new javax.swing.JButton();
        jBotonModRen = new javax.swing.JButton();
        jBotonElimRen = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablaDoc = new javax.swing.JTable();
        jBotonActGrillaDoc = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuDocente = new javax.swing.JMenu();
        jMenuRegistrarDoc = new javax.swing.JMenuItem();
        jMenuModificarDoc = new javax.swing.JMenuItem();
        jMenuEliminarDoc = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenu5 = new javax.swing.JMenu();
        jMenuRegMat = new javax.swing.JMenuItem();
        jMenuModMat = new javax.swing.JMenuItem();
        jMenuElimMat = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuRegUser = new javax.swing.JMenuItem();
        jMenuModUser = new javax.swing.JMenuItem();
        jMenuElimUser = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(840, 640));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Gestionar Docentes"));

        jBotonRegDoc.setText("Registrar");
        jBotonRegDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonRegDocActionPerformed(evt);
            }
        });

        jBotonModDoc.setText("Modificar");
        jBotonModDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonModDocActionPerformed(evt);
            }
        });

        jBotonElimDoc.setText("Eliminar");
        jBotonElimDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonElimDocActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBotonRegDoc, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
            .addComponent(jBotonModDoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jBotonElimDoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jBotonRegDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBotonModDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBotonElimDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Gestionar Horas"));

        jBotonAsignHora.setText("Asignar");
        jBotonAsignHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonAsignHoraActionPerformed(evt);
            }
        });

        jBotonModHora.setText("Modificar");

        jBotonElimHora.setText("Eliminar");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBotonAsignHora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jBotonModHora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jBotonElimHora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jBotonAsignHora, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBotonModHora, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBotonElimHora, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Gestionar Licencias"));

        jBotonRegLic.setText("Registrar");

        jBotonModLic.setText("Modificar");

        jBotonElimLic.setText("Eliminar");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBotonRegLic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jBotonModLic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jBotonElimLic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jBotonRegLic, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBotonModLic, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBotonElimLic, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Gestionar Renuncias"));

        jBotonRegRen.setText("Registrar");
        jBotonRegRen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonRegRenActionPerformed(evt);
            }
        });

        jBotonModRen.setText("Modificar");

        jBotonElimRen.setText("Eliminar");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBotonRegRen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jBotonModRen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jBotonElimRen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jBotonRegRen, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBotonModRen, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBotonElimRen, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 81, Short.MAX_VALUE))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Listado de Docentes"));

        jTablaDoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Legajo", "Nombre y Apellido", "Materia", "Estado"
            }
        ));
        jTablaDoc.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTablaDocPropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(jTablaDoc);

        jBotonActGrillaDoc.setText("Actualizar Grilla");

        jLabel1.setText("NOTA:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jBotonActGrillaDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 672, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBotonActGrillaDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1))
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jMenuDocente.setText("Docentes");
        jMenuDocente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuDocenteMouseClicked(evt);
            }
        });
        jMenuDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuDocenteActionPerformed(evt);
            }
        });

        jMenuRegistrarDoc.setText("Registrar");
        jMenuRegistrarDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRegistrarDocActionPerformed(evt);
            }
        });
        jMenuDocente.add(jMenuRegistrarDoc);

        jMenuModificarDoc.setText("Modificar");
        jMenuModificarDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuModificarDocActionPerformed(evt);
            }
        });
        jMenuDocente.add(jMenuModificarDoc);

        jMenuEliminarDoc.setText("Eliminar");
        jMenuEliminarDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEliminarDocActionPerformed(evt);
            }
        });
        jMenuDocente.add(jMenuEliminarDoc);
        jMenuDocente.add(jSeparator1);

        jMenuBar1.add(jMenuDocente);

        jMenu5.setText("Materias");

        jMenuRegMat.setText("Registrar");
        jMenuRegMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRegMatActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuRegMat);

        jMenuModMat.setText("Modificar");
        jMenuModMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuModMatActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuModMat);

        jMenuElimMat.setText("Eliminar");
        jMenuElimMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuElimMatActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuElimMat);

        jMenuBar1.add(jMenu5);

        jMenu7.setText("Usuarios");

        jMenuRegUser.setText("Registrar");
        jMenuRegUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRegUserActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuRegUser);

        jMenuModUser.setText("Modificar");
        jMenuModUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuModUserActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuModUser);

        jMenuElimUser.setText("Eliminar");
        jMenu7.add(jMenuElimUser);

        jMenuBar1.add(jMenu7);

        jMenu6.setText("Ayuda");
        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuDocenteActionPerformed

    }//GEN-LAST:event_jMenuDocenteActionPerformed

    private void jMenuDocenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuDocenteMouseClicked

    }//GEN-LAST:event_jMenuDocenteMouseClicked

    private void jMenuModificarDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuModificarDocActionPerformed

    }//GEN-LAST:event_jMenuModificarDocActionPerformed

    private void jMenuRegistrarDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRegistrarDocActionPerformed

    }//GEN-LAST:event_jMenuRegistrarDocActionPerformed

    private void jMenuEliminarDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuEliminarDocActionPerformed
        
    }//GEN-LAST:event_jMenuEliminarDocActionPerformed

    private void jMenuRegUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRegUserActionPerformed
        IUPrincipalUsuario miPrincipalUsuario = new IUPrincipalUsuario();
        miPrincipalUsuario.setVisible(true);
    }//GEN-LAST:event_jMenuRegUserActionPerformed

    private void jMenuModUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuModUserActionPerformed
        IUPrincipalUsuario miPrincipalUsuario = new IUPrincipalUsuario();
        miPrincipalUsuario.setVisible(true);
    }//GEN-LAST:event_jMenuModUserActionPerformed

    private void jBotonElimDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonElimDocActionPerformed
        IUPrincipalUsuario miPrincipalUsuario = new IUPrincipalUsuario();
        miPrincipalUsuario.setVisible(true);
        //miEliminarDocente.setVisible(true);    }//GEN-LAST:event_jBotonElimDocActionPerformed
    }
    
    private void jBotonRegRenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonRegRenActionPerformed
    }//GEN-LAST:event_jBotonRegRenActionPerformed

    private void jBotonRegDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonRegDocActionPerformed
        IURegistrarDocente miRegistrarDocente = new IURegistrarDocente();
        miRegistrarDocente.setVisible(true);

    }//GEN-LAST:event_jBotonRegDocActionPerformed

    private void jBotonModDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonModDocActionPerformed
        IUModificarDocente miModificarDocente = new IUModificarDocente();
        miModificarDocente.setVisible(true);
    }//GEN-LAST:event_jBotonModDocActionPerformed

    private void jBotonAsignHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonAsignHoraActionPerformed
        IUAsignarHoraDocente miAsignarHoraDocente = new IUAsignarHoraDocente();
        miAsignarHoraDocente.setVisible(true);
    }//GEN-LAST:event_jBotonAsignHoraActionPerformed

    private void jMenuRegMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRegMatActionPerformed
        IUPrincipalMateria miPrincipalMateria = new IUPrincipalMateria();
        miPrincipalMateria.setVisible(true);
    }//GEN-LAST:event_jMenuRegMatActionPerformed

    private void jMenuModMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuModMatActionPerformed
        IUPrincipalMateria miPrincipalMateria = new IUPrincipalMateria();
        miPrincipalMateria.setVisible(true);
    }//GEN-LAST:event_jMenuModMatActionPerformed

    private void jMenuElimMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuElimMatActionPerformed
        IUPrincipalMateria miPrincipalMateria = new IUPrincipalMateria();
        miPrincipalMateria.setVisible(true);
    }//GEN-LAST:event_jMenuElimMatActionPerformed

    private void jTablaDocPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTablaDocPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jTablaDocPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try{
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IUPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IUPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IUPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IUPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IUPrincipal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBotonActGrillaDoc;
    private javax.swing.JButton jBotonAsignHora;
    private javax.swing.JButton jBotonElimDoc;
    private javax.swing.JButton jBotonElimHora;
    private javax.swing.JButton jBotonElimLic;
    private javax.swing.JButton jBotonElimRen;
    private javax.swing.JButton jBotonModDoc;
    private javax.swing.JButton jBotonModHora;
    private javax.swing.JButton jBotonModLic;
    private javax.swing.JButton jBotonModRen;
    private javax.swing.JButton jBotonRegDoc;
    private javax.swing.JButton jBotonRegLic;
    private javax.swing.JButton jBotonRegRen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuDocente;
    private javax.swing.JMenuItem jMenuElimMat;
    private javax.swing.JMenuItem jMenuElimUser;
    private javax.swing.JMenuItem jMenuEliminarDoc;
    private javax.swing.JMenuItem jMenuModMat;
    private javax.swing.JMenuItem jMenuModUser;
    private javax.swing.JMenuItem jMenuModificarDoc;
    private javax.swing.JMenuItem jMenuRegMat;
    private javax.swing.JMenuItem jMenuRegUser;
    private javax.swing.JMenuItem jMenuRegistrarDoc;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTable jTablaDoc;
    // End of variables declaration//GEN-END:variables
}
