/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import hibernate.mapping.Docente;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JOptionPane;
import vista.renuncia.IUDRenunciaRegistrar;
import vista.licencia.IUDLicenciaRegistrar;
import vista.designacion.IUDHoraEliminar;
import vista.designacion.IUDHoraDesignar;
import vista.docente.IUDocenteModificar;
import vista.docente.IUDocenteRegistrar;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import vista.designacion.IUDHoraConsultar;
import vista.docente.IUDocenteConsultar;
import vista.docente.IUDocenteEliminar;
import vista.licencia.IUDLicenciaConsultar;
import vista.licencia.IUDLicenciaEliminar;
import vista.licencia.IUDLicenciaModificar;
import vista.materia.IUMateriaPrincipal;
import vista.renuncia.IUDRenunciaConsultar;
import vista.renuncia.IUDRenunciaEliminar;
import vista.renuncia.IUDRenunciaModificar;
import vista.usuario.IUUsuarioPrincipal;

/**
 *
 * @author ILS
 */
public class IUPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form IUPrincipal
     */
    public IUPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
        cargarTabla();

        //LISTENERS
        jTablaDoc.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e){
                jBotonModDoc.setEnabled(true);
                jBotonConsDoc.setEnabled(true);
                jBotonElimDoc.setEnabled(true);
                jBotonAsignHora.setEnabled(true);
                jBotonConsHora.setEnabled(true);
                jBotonConsLic.setEnabled(true);
                jBotonConsRen.setEnabled(true);
                jBotonElimDoc.setEnabled(true);
                jBotonElimHora.setEnabled(true);
                jBotonElimLic.setEnabled(true);
                jBotonElimRen.setEnabled(true);
                jBotonModDoc.setEnabled(true);
                jBotonModLic.setEnabled(true);
                jBotonModRen.setEnabled(true);
                jBotonRegDoc.setEnabled(true);
                jBotonRegLic.setEnabled(true);
                jBotonRegRen.setEnabled(true);
                jBotonSitRev.setEnabled(true);
            }
            
            public void mousePressed(MouseEvent e){
                if (e.getClickCount()==2){
                    //JTable target = (JTable)e.getSource();
                    //int row = target.getSelectedRow();
                    //int column = target.getSelectedColumn();
                    JOptionPane.showMessageDialog(null, "aqui dispara la consulta del docente");
                }
            }
        }
                );
        
    }
    
        //PROCEDIMIENTOS

    private void cargarTabla()
    {
        DefaultTableModel modeloTablaDoc = (DefaultTableModel)jTablaDoc.getModel();
        
        String[] datos = new String[8];
        datos[0]="aa";
        datos[1]="bb";
        datos[2]="cc";
        modeloTablaDoc.addRow(datos);
        //limpiar();
        //List<Docente> listadoDocente = miDocenteDAO.selectAll();
        //DefaultTableModel modelo=(DefaultTableModel)tblTablaAlumno.getModel();
        //String[] datosDocente=new String[8];

        //for (Docente docente:listadoDocente){
            //datosDocente[0]=String.valueOf(docente.getId());
            //datosDocente[1]=docente.getDni();
            //datosDocente[2]=docente.getApellido();
            //datosDocente[3]=docente.getNombre();
            //datosDocente[4]=String.valueOf(docente.getEdad());
            
            //modeloTablaDoc.addRow(datosDocente);
        //}

    }

    private void actualizarTabla()
    {
    }
    
    private void limpiarTabla()
    {
        DefaultTableModel modeloTablaDoc = (DefaultTableModel)jTablaDoc.getModel();
        while(jTablaDoc.getRowCount() != 0)
                modeloTablaDoc.removeRow(0);
    }
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jBotonSitRev = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jBotonAsignHora = new javax.swing.JButton();
        jBotonElimHora = new javax.swing.JButton();
        jBotonConsHora = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jBotonRegLic = new javax.swing.JButton();
        jBotonModLic = new javax.swing.JButton();
        jBotonElimLic = new javax.swing.JButton();
        jBotonConsLic = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jBotonRegRen = new javax.swing.JButton();
        jBotonModRen = new javax.swing.JButton();
        jBotonElimRen = new javax.swing.JButton();
        jBotonConsRen = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablaDoc = new javax.swing.JTable();
        jBotonActGrillaDoc = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jBotonRegDoc = new javax.swing.JButton();
        jBotonModDoc = new javax.swing.JButton();
        jBotonConsDoc = new javax.swing.JButton();
        jBotonElimDoc = new javax.swing.JButton();
        jToolBar1 = new javax.swing.JToolBar();
        jBotonMaterias = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        jBotonUsuarios = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jBotonAyuda = new javax.swing.JButton();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(840, 640));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Gestionar Docentes"));

        jBotonSitRev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/16x16/book.png"))); // NOI18N
        jBotonSitRev.setText("Situacion de Revista");
        jBotonSitRev.setEnabled(false);
        jBotonSitRev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonSitRevActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBotonSitRev, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBotonSitRev, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel5.setBackground(new java.awt.Color(204, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Gestionar Horas"));

        jBotonAsignHora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/16x16/clock_add.png"))); // NOI18N
        jBotonAsignHora.setText("Designar");
        jBotonAsignHora.setEnabled(false);
        jBotonAsignHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonAsignHoraActionPerformed(evt);
            }
        });

        jBotonElimHora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/16x16/clock_delete.png"))); // NOI18N
        jBotonElimHora.setText("Eliminar");
        jBotonElimHora.setEnabled(false);
        jBotonElimHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonElimHoraActionPerformed(evt);
            }
        });

        jBotonConsHora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/16x16/clock.png"))); // NOI18N
        jBotonConsHora.setText("Consultar");
        jBotonConsHora.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBotonConsHora.setEnabled(false);
        jBotonConsHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonConsHoraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBotonAsignHora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jBotonElimHora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jBotonConsHora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jBotonConsHora, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBotonAsignHora, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBotonElimHora, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        jPanel6.setBackground(new java.awt.Color(204, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Gestionar Licencias"));

        jBotonRegLic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/16x16/report_add.png"))); // NOI18N
        jBotonRegLic.setText("Registrar");
        jBotonRegLic.setEnabled(false);
        jBotonRegLic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonRegLicActionPerformed(evt);
            }
        });

        jBotonModLic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/16x16/report_edit.png"))); // NOI18N
        jBotonModLic.setText("Modificar");
        jBotonModLic.setEnabled(false);
        jBotonModLic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonModLicActionPerformed(evt);
            }
        });

        jBotonElimLic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/16x16/report_delete.png"))); // NOI18N
        jBotonElimLic.setText("Eliminar");
        jBotonElimLic.setEnabled(false);
        jBotonElimLic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonElimLicActionPerformed(evt);
            }
        });

        jBotonConsLic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/16x16/report.png"))); // NOI18N
        jBotonConsLic.setText("Consultar");
        jBotonConsLic.setEnabled(false);
        jBotonConsLic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonConsLicActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBotonRegLic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jBotonModLic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jBotonElimLic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jBotonConsLic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jBotonConsLic, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBotonRegLic, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBotonModLic, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBotonElimLic, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel8.setBackground(new java.awt.Color(204, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Gestionar Renuncias"));

        jBotonRegRen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/16x16/hourglass_add.png"))); // NOI18N
        jBotonRegRen.setText("Registrar");
        jBotonRegRen.setEnabled(false);
        jBotonRegRen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonRegRenActionPerformed(evt);
            }
        });

        jBotonModRen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/16x16/hourglass_go.png"))); // NOI18N
        jBotonModRen.setText("Modificar");
        jBotonModRen.setEnabled(false);
        jBotonModRen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonModRenActionPerformed(evt);
            }
        });

        jBotonElimRen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/16x16/hourglass_delete.png"))); // NOI18N
        jBotonElimRen.setText("Eliminar");
        jBotonElimRen.setEnabled(false);
        jBotonElimRen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonElimRenActionPerformed(evt);
            }
        });

        jBotonConsRen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/16x16/hourglass.png"))); // NOI18N
        jBotonConsRen.setText("Consultar");
        jBotonConsRen.setEnabled(false);
        jBotonConsRen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonConsRenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBotonRegRen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jBotonModRen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jBotonElimRen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jBotonConsRen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jBotonConsRen, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBotonRegRen, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBotonModRen, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBotonElimRen, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel4.setBackground(new java.awt.Color(204, 255, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Listado de Profesores"));

        jTablaDoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre y Apellido", "Materia", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTablaDoc.setSurrendersFocusOnKeystroke(true);
        jTablaDoc.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTablaDocPropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(jTablaDoc);
        jTablaDoc.getColumnModel().getColumn(0).setResizable(false);

        jBotonActGrillaDoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/16x16/arrow_refresh.png"))); // NOI18N
        jBotonActGrillaDoc.setText("Actualizar Grilla");

        jLabel1.setText("NOTA:");

        jBotonRegDoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/16x16/add.png"))); // NOI18N
        jBotonRegDoc.setText("Registrar");
        jBotonRegDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonRegDocActionPerformed(evt);
            }
        });

        jBotonModDoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/16x16/pencil.png"))); // NOI18N
        jBotonModDoc.setText("Modificar");
        jBotonModDoc.setEnabled(false);
        jBotonModDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonModDocActionPerformed(evt);
            }
        });

        jBotonConsDoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/16x16/group.png"))); // NOI18N
        jBotonConsDoc.setText("Consultar");
        jBotonConsDoc.setEnabled(false);
        jBotonConsDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonConsDocActionPerformed(evt);
            }
        });

        jBotonElimDoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/16x16/delete.png"))); // NOI18N
        jBotonElimDoc.setText("Eliminar");
        jBotonElimDoc.setEnabled(false);
        jBotonElimDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonElimDocActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 624, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jBotonActGrillaDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jBotonRegDoc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBotonConsDoc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBotonModDoc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBotonElimDoc)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBotonRegDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBotonModDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBotonConsDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBotonElimDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBotonActGrillaDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jToolBar1.setRollover(true);

        jBotonMaterias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/16x16/book_open.png"))); // NOI18N
        jBotonMaterias.setText("Materias");
        jBotonMaterias.setFocusable(false);
        jBotonMaterias.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBotonMaterias.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBotonMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonMateriasActionPerformed(evt);
            }
        });
        jToolBar1.add(jBotonMaterias);
        jToolBar1.add(jSeparator3);

        jBotonUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/16x16/folder_user.png"))); // NOI18N
        jBotonUsuarios.setText("Usuarios");
        jBotonUsuarios.setFocusable(false);
        jBotonUsuarios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBotonUsuarios.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBotonUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonUsuariosActionPerformed(evt);
            }
        });
        jToolBar1.add(jBotonUsuarios);
        jToolBar1.add(jSeparator1);

        jBotonAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/16x16/help.png"))); // NOI18N
        jBotonAyuda.setText("Ayuda");
        jBotonAyuda.setFocusable(false);
        jBotonAyuda.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBotonAyuda.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBotonAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonAyudaActionPerformed(evt);
            }
        });
        jToolBar1.add(jBotonAyuda);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    //INTERFAZ
    private void jBotonElimDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonElimDocActionPerformed
        IUDocenteEliminar miEliminarDocente = new IUDocenteEliminar();
        miEliminarDocente.setVisible(true);
        //miEliminarDocente.setVisible(true);    }//GEN-LAST:event_jBotonElimDocActionPerformed
        
    }
    
    private void jBotonRegRenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonRegRenActionPerformed
        IUDRenunciaRegistrar miRegistrarRenunciaDocente = new IUDRenunciaRegistrar();
        miRegistrarRenunciaDocente.setVisible(true);
    }//GEN-LAST:event_jBotonRegRenActionPerformed

    private void jBotonRegDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonRegDocActionPerformed
        IUDocenteRegistrar miRegistrarDocente = new IUDocenteRegistrar();
        miRegistrarDocente.setVisible(true);

    }//GEN-LAST:event_jBotonRegDocActionPerformed

    private void jBotonModDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonModDocActionPerformed
        IUDocenteModificar miModificarDocente = new IUDocenteModificar();
        miModificarDocente.setVisible(true);
        
        
        
    }//GEN-LAST:event_jBotonModDocActionPerformed

    private void jBotonAsignHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonAsignHoraActionPerformed
        IUDHoraDesignar miDesignarHoraDocente = new IUDHoraDesignar();
        miDesignarHoraDocente.setVisible(true);      

    }//GEN-LAST:event_jBotonAsignHoraActionPerformed

    private void jBotonElimHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonElimHoraActionPerformed
        IUDHoraEliminar miEliminarHoraDocente = new IUDHoraEliminar();
        miEliminarHoraDocente.setVisible(true);
    }//GEN-LAST:event_jBotonElimHoraActionPerformed

    private void jBotonRegLicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonRegLicActionPerformed
        IUDLicenciaRegistrar miRegistrarLicenciaDocente = new IUDLicenciaRegistrar();
        miRegistrarLicenciaDocente.setVisible(true);
    }//GEN-LAST:event_jBotonRegLicActionPerformed

    private void jBotonElimLicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonElimLicActionPerformed
        IUDLicenciaEliminar miEliminarLicencia = new IUDLicenciaEliminar();
        miEliminarLicencia.setVisible(true);
    }//GEN-LAST:event_jBotonElimLicActionPerformed

    private void jBotonModLicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonModLicActionPerformed
        IUDLicenciaModificar miModificarLicencia = new IUDLicenciaModificar();
        miModificarLicencia.setVisible(true);
    }//GEN-LAST:event_jBotonModLicActionPerformed

    private void jBotonSitRevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonSitRevActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBotonSitRevActionPerformed

    private void jBotonMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonMateriasActionPerformed
        IUMateriaPrincipal miPrincipalMateria = new IUMateriaPrincipal();
        miPrincipalMateria.setVisible(true);
        miPrincipalMateria.setTitulo("GESTION DE MATERIAS");
    }//GEN-LAST:event_jBotonMateriasActionPerformed

    private void jBotonUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonUsuariosActionPerformed
        IUUsuarioPrincipal miUsuarioPrincipal = new IUUsuarioPrincipal();
        miUsuarioPrincipal.setVisible(true);
    }//GEN-LAST:event_jBotonUsuariosActionPerformed

    private void jTablaDocPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTablaDocPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jTablaDocPropertyChange

    private void jBotonConsHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonConsHoraActionPerformed
        IUDHoraConsultar miHoraConsultar = new IUDHoraConsultar();
        miHoraConsultar.setVisible(true);
    }//GEN-LAST:event_jBotonConsHoraActionPerformed

    private void jBotonConsLicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonConsLicActionPerformed
        IUDLicenciaConsultar miConsultarLicencia = new IUDLicenciaConsultar();
        miConsultarLicencia.setVisible(true);
    }//GEN-LAST:event_jBotonConsLicActionPerformed

    private void jBotonConsRenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonConsRenActionPerformed
        IUDRenunciaConsultar miConsultarRenuncia = new IUDRenunciaConsultar();
        miConsultarRenuncia.setVisible(true);        
    }//GEN-LAST:event_jBotonConsRenActionPerformed

    private void jBotonConsDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonConsDocActionPerformed
        if (jBotonConsDoc.isEnabled() == true)    
        {
            Docente miDocente = new Docente();
            int coddocente;
            int fila = jTablaDoc.getSelectedRow();
            int columna = 0;              
            coddocente = Integer.parseInt(jTablaDoc.getValueAt(fila, columna).toString());
                
            miDocente = miDocenteDAO.consultarDocente(coddocente);
            
            IUDocenteConsultar miConsultarDocente = new IUDocenteConsultar(null,true,miDocente);
            miConsultarDocente.setVisible(true);
        }
    }//GEN-LAST:event_jBotonConsDocActionPerformed

    private void jBotonModRenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonModRenActionPerformed
        IUDRenunciaModificar miModificarRenuncia = new IUDRenunciaModificar();
        miModificarRenuncia.setVisible(true);
    }//GEN-LAST:event_jBotonModRenActionPerformed

    private void jBotonElimRenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonElimRenActionPerformed
        IUDRenunciaEliminar miEliminarRenuncia = new IUDRenunciaEliminar();
        miEliminarRenuncia.setVisible(true);
    }//GEN-LAST:event_jBotonElimRenActionPerformed

    private void jBotonAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonAyudaActionPerformed
        JOptionPane.showMessageDialog(null, "INGENIERO INFORMATICO IGNACIO SARAVIA");

    }//GEN-LAST:event_jBotonAyudaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try{
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IUPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IUPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IUPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IUPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IUPrincipal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBotonActGrillaDoc;
    private javax.swing.JButton jBotonAsignHora;
    private javax.swing.JButton jBotonAyuda;
    private javax.swing.JButton jBotonConsDoc;
    private javax.swing.JButton jBotonConsHora;
    private javax.swing.JButton jBotonConsLic;
    private javax.swing.JButton jBotonConsRen;
    private javax.swing.JButton jBotonElimDoc;
    private javax.swing.JButton jBotonElimHora;
    private javax.swing.JButton jBotonElimLic;
    private javax.swing.JButton jBotonElimRen;
    private javax.swing.JButton jBotonMaterias;
    private javax.swing.JButton jBotonModDoc;
    private javax.swing.JButton jBotonModLic;
    private javax.swing.JButton jBotonModRen;
    private javax.swing.JButton jBotonRegDoc;
    private javax.swing.JButton jBotonRegLic;
    private javax.swing.JButton jBotonRegRen;
    private javax.swing.JButton jBotonSitRev;
    private javax.swing.JButton jBotonUsuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JTable jTablaDoc;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables



}
