package hibernate.mapping;
// Generated 29-oct-2014 19:13:10 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Docente generated by hbm2java
 */
public class Docente  implements java.io.Serializable {


     private int coddocente;
     private Persona persona;
     private String titulo;
     private Date fechatitulo;
     private int totalhorasactivas;
     private String estado;
     private Date fechaingreso;
     private Set horadesignadas = new HashSet(0);

    public Docente() {
    }

	
    public Docente(int coddocente, Persona persona, String titulo, Date fechatitulo, int totalhorasactivas, String estado, Date fechaingreso) {
        this.coddocente = coddocente;
        this.persona = persona;
        this.titulo = titulo;
        this.fechatitulo = fechatitulo;
        this.totalhorasactivas = totalhorasactivas;
        this.estado = estado;
        this.fechaingreso = fechaingreso;
    }
    public Docente(int coddocente, Persona persona, String titulo, Date fechatitulo, int totalhorasactivas, String estado, Date fechaingreso, Set horadesignadas) {
       this.coddocente = coddocente;
       this.persona = persona;
       this.titulo = titulo;
       this.fechatitulo = fechatitulo;
       this.totalhorasactivas = totalhorasactivas;
       this.estado = estado;
       this.fechaingreso = fechaingreso;
       this.horadesignadas = horadesignadas;
    }
   
    public int getCoddocente() {
        return this.coddocente;
    }
    
    public void setCoddocente(int coddocente) {
        this.coddocente = coddocente;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public Date getFechatitulo() {
        return this.fechatitulo;
    }
    
    public void setFechatitulo(Date fechatitulo) {
        this.fechatitulo = fechatitulo;
    }
    public int getTotalhorasactivas() {
        return this.totalhorasactivas;
    }
    
    public void setTotalhorasactivas(int totalhorasactivas) {
        this.totalhorasactivas = totalhorasactivas;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Date getFechaingreso() {
        return this.fechaingreso;
    }
    
    public void setFechaingreso(Date fechaingreso) {
        this.fechaingreso = fechaingreso;
    }
    public Set getHoradesignadas() {
        return this.horadesignadas;
    }
    
    public void setHoradesignadas(Set horadesignadas) {
        this.horadesignadas = horadesignadas;
    }

    public void registrarDocente()
    {
    }
    
    public void consultarDocente()
    {
        
    }
    
    public void modificarDocente()
    {
        
    }
    
    public void eliminarDocente()
    {
        
    }
    
    public void verificarDocente()
    {
        
    }
    
    public void verificarCargaHoraria()
    {
        
    }
    
    public void verificarEstado()
    {
        
    }
    
    public void actualizarEstado()
    {
    }


}


