package hibernate.mapping;
// Generated 29-oct-2014 19:13:10 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Horadesignada generated by hbm2java
 */
public class Horadesignada  implements java.io.Serializable {


     private int codhoradesignada;
     private Usuario usuario;
     private Situacionrevista situacionrevista;
     private Materia materia;
     private Docente docente;
     private Date fechadesignacion;
     private Date fechahasta;
     private Date fechaoperacion;
     private String estadohoras;
     private String caracterdocente;
     private String normativa;
     private String observaciones;
     private Set licencias = new HashSet(0);
     private Set renuncias = new HashSet(0);

    public Horadesignada() {
    }

	
    public Horadesignada(int codhoradesignada, Usuario usuario, Situacionrevista situacionrevista, Materia materia, Docente docente, Date fechadesignacion, Date fechahasta, Date fechaoperacion, String estadohoras, String caracterdocente, String normativa) {
        this.codhoradesignada = codhoradesignada;
        this.usuario = usuario;
        this.situacionrevista = situacionrevista;
        this.materia = materia;
        this.docente = docente;
        this.fechadesignacion = fechadesignacion;
        this.fechahasta = fechahasta;
        this.fechaoperacion = fechaoperacion;
        this.estadohoras = estadohoras;
        this.caracterdocente = caracterdocente;
        this.normativa = normativa;
    }
    public Horadesignada(int codhoradesignada, Usuario usuario, Situacionrevista situacionrevista, Materia materia, Docente docente, Date fechadesignacion, Date fechahasta, Date fechaoperacion, String estadohoras, String caracterdocente, String normativa, String observaciones, Set licencias, Set renuncias) {
       this.codhoradesignada = codhoradesignada;
       this.usuario = usuario;
       this.situacionrevista = situacionrevista;
       this.materia = materia;
       this.docente = docente;
       this.fechadesignacion = fechadesignacion;
       this.fechahasta = fechahasta;
       this.fechaoperacion = fechaoperacion;
       this.estadohoras = estadohoras;
       this.caracterdocente = caracterdocente;
       this.normativa = normativa;
       this.observaciones = observaciones;
       this.licencias = licencias;
       this.renuncias = renuncias;
    }
   
    public int getCodhoradesignada() {
        return this.codhoradesignada;
    }
    
    public void setCodhoradesignada(int codhoradesignada) {
        this.codhoradesignada = codhoradesignada;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Situacionrevista getSituacionrevista() {
        return this.situacionrevista;
    }
    
    public void setSituacionrevista(Situacionrevista situacionrevista) {
        this.situacionrevista = situacionrevista;
    }
    public Materia getMateria() {
        return this.materia;
    }
    
    public void setMateria(Materia materia) {
        this.materia = materia;
    }
    public Docente getDocente() {
        return this.docente;
    }
    
    public void setDocente(Docente docente) {
        this.docente = docente;
    }
    public Date getFechadesignacion() {
        return this.fechadesignacion;
    }
    
    public void setFechadesignacion(Date fechadesignacion) {
        this.fechadesignacion = fechadesignacion;
    }
    public Date getFechahasta() {
        return this.fechahasta;
    }
    
    public void setFechahasta(Date fechahasta) {
        this.fechahasta = fechahasta;
    }
    public Date getFechaoperacion() {
        return this.fechaoperacion;
    }
    
    public void setFechaoperacion(Date fechaoperacion) {
        this.fechaoperacion = fechaoperacion;
    }
    public String getEstadohoras() {
        return this.estadohoras;
    }
    
    public void setEstadohoras(String estadohoras) {
        this.estadohoras = estadohoras;
    }
    public String getCaracterdocente() {
        return this.caracterdocente;
    }
    
    public void setCaracterdocente(String caracterdocente) {
        this.caracterdocente = caracterdocente;
    }
    public String getNormativa() {
        return this.normativa;
    }
    
    public void setNormativa(String normativa) {
        this.normativa = normativa;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
    public Set getLicencias() {
        return this.licencias;
    }
    
    public void setLicencias(Set licencias) {
        this.licencias = licencias;
    }
    public Set getRenuncias() {
        return this.renuncias;
    }
    
    public void setRenuncias(Set renuncias) {
        this.renuncias = renuncias;
    }

    public void designarHoras()
    {
        
    }
      
    public void eliminarHora()
    {
    }
    
    public void consultarHora()
    {
        
    }
    
    public void verificarEstado()
    {
        
    }
    
    public void actualizarEstado()
    {
        
    }


}


