package hibernate.mapping;
// Generated 29-oct-2014 19:13:10 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Licencia generated by hbm2java
 */
public class Licencia  implements java.io.Serializable {


     private int codlicencia;
     private Horadesignada horadesignada;
     private Date fechadesde;
     private Date fechahasta;
     private Date fechaoperacion;
     private String normativa;
     private String observaciones;
     private String estado;

    public Licencia() {
    }

	
    public Licencia(int codlicencia, Horadesignada horadesignada, Date fechadesde, Date fechahasta, Date fechaoperacion, String normativa, String estado) {
        this.codlicencia = codlicencia;
        this.horadesignada = horadesignada;
        this.fechadesde = fechadesde;
        this.fechahasta = fechahasta;
        this.fechaoperacion = fechaoperacion;
        this.normativa = normativa;
        this.estado = estado;
    }
    public Licencia(int codlicencia, Horadesignada horadesignada, Date fechadesde, Date fechahasta, Date fechaoperacion, String normativa, String observaciones, String estado) {
       this.codlicencia = codlicencia;
       this.horadesignada = horadesignada;
       this.fechadesde = fechadesde;
       this.fechahasta = fechahasta;
       this.fechaoperacion = fechaoperacion;
       this.normativa = normativa;
       this.observaciones = observaciones;
       this.estado = estado;
    }
   
    public int getCodlicencia() {
        return this.codlicencia;
    }
    
    public void setCodlicencia(int codlicencia) {
        this.codlicencia = codlicencia;
    }
    public Horadesignada getHoradesignada() {
        return this.horadesignada;
    }
    
    public void setHoradesignada(Horadesignada horadesignada) {
        this.horadesignada = horadesignada;
    }
    public Date getFechadesde() {
        return this.fechadesde;
    }
    
    public void setFechadesde(Date fechadesde) {
        this.fechadesde = fechadesde;
    }
    public Date getFechahasta() {
        return this.fechahasta;
    }
    
    public void setFechahasta(Date fechahasta) {
        this.fechahasta = fechahasta;
    }
    public Date getFechaoperacion() {
        return this.fechaoperacion;
    }
    
    public void setFechaoperacion(Date fechaoperacion) {
        this.fechaoperacion = fechaoperacion;
    }
    public String getNormativa() {
        return this.normativa;
    }
    
    public void setNormativa(String normativa) {
        this.normativa = normativa;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }

        public void registrarLicencia()
    {
        
    }
    
    public void consultarLicencia()
    {
        
    }
    
    public void modificarLicencia()
    {
        
    }
    
    public void eliminarLicencia()
    {
        
    }

    public void verificarLicencia()
    {
        
    }
    
    public void actualizarEstado()
    {
        
    }
   


}


