package hibernate.mapping;
// Generated 29-oct-2014 19:13:10 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Renuncia generated by hbm2java
 */
public class Renuncia  implements java.io.Serializable {


     private int codrenuncia;
     private Horadesignada horadesignada;
     private Date fecharenuncia;
     private Date fechaoperacion;
     private String normativa;
     private String observaciones;
     private String estado;

    public Renuncia() {
    }

	
    public Renuncia(int codrenuncia, Horadesignada horadesignada, Date fecharenuncia, Date fechaoperacion, String normativa, String estado) {
        this.codrenuncia = codrenuncia;
        this.horadesignada = horadesignada;
        this.fecharenuncia = fecharenuncia;
        this.fechaoperacion = fechaoperacion;
        this.normativa = normativa;
        this.estado = estado;
    }
    public Renuncia(int codrenuncia, Horadesignada horadesignada, Date fecharenuncia, Date fechaoperacion, String normativa, String observaciones, String estado) {
       this.codrenuncia = codrenuncia;
       this.horadesignada = horadesignada;
       this.fecharenuncia = fecharenuncia;
       this.fechaoperacion = fechaoperacion;
       this.normativa = normativa;
       this.observaciones = observaciones;
       this.estado = estado;
    }
   
    public int getCodrenuncia() {
        return this.codrenuncia;
    }
    
    public void setCodrenuncia(int codrenuncia) {
        this.codrenuncia = codrenuncia;
    }
    public Horadesignada getHoradesignada() {
        return this.horadesignada;
    }
    
    public void setHoradesignada(Horadesignada horadesignada) {
        this.horadesignada = horadesignada;
    }
    public Date getFecharenuncia() {
        return this.fecharenuncia;
    }
    
    public void setFecharenuncia(Date fecharenuncia) {
        this.fecharenuncia = fecharenuncia;
    }
    public Date getFechaoperacion() {
        return this.fechaoperacion;
    }
    
    public void setFechaoperacion(Date fechaoperacion) {
        this.fechaoperacion = fechaoperacion;
    }
    public String getNormativa() {
        return this.normativa;
    }
    
    public void setNormativa(String normativa) {
        this.normativa = normativa;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


