package hibernate.mapping;
// Generated 29-oct-2014 19:13:10 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int codusuario;
     private Persona persona;
     private String nombreusuario;
     private String password;
     private String tipousuario;
     private String ocupacion;
     private Date fechaingreso;
     private String estado;
     private Set situacionrevistas = new HashSet(0);
     private Set horadesignadas = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(int codusuario, Persona persona, String nombreusuario, String password, String tipousuario, String ocupacion, Date fechaingreso, String estado) {
        this.codusuario = codusuario;
        this.persona = persona;
        this.nombreusuario = nombreusuario;
        this.password = password;
        this.tipousuario = tipousuario;
        this.ocupacion = ocupacion;
        this.fechaingreso = fechaingreso;
        this.estado = estado;
    }
    public Usuario(int codusuario, Persona persona, String nombreusuario, String password, String tipousuario, String ocupacion, Date fechaingreso, String estado, Set situacionrevistas, Set horadesignadas) {
       this.codusuario = codusuario;
       this.persona = persona;
       this.nombreusuario = nombreusuario;
       this.password = password;
       this.tipousuario = tipousuario;
       this.ocupacion = ocupacion;
       this.fechaingreso = fechaingreso;
       this.estado = estado;
       this.situacionrevistas = situacionrevistas;
       this.horadesignadas = horadesignadas;
    }
   
    public int getCodusuario() {
        return this.codusuario;
    }
    
    public void setCodusuario(int codusuario) {
        this.codusuario = codusuario;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public String getNombreusuario() {
        return this.nombreusuario;
    }
    
    public void setNombreusuario(String nombreusuario) {
        this.nombreusuario = nombreusuario;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getTipousuario() {
        return this.tipousuario;
    }
    
    public void setTipousuario(String tipousuario) {
        this.tipousuario = tipousuario;
    }
    public String getOcupacion() {
        return this.ocupacion;
    }
    
    public void setOcupacion(String ocupacion) {
        this.ocupacion = ocupacion;
    }
    public Date getFechaingreso() {
        return this.fechaingreso;
    }
    
    public void setFechaingreso(Date fechaingreso) {
        this.fechaingreso = fechaingreso;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getSituacionrevistas() {
        return this.situacionrevistas;
    }
    
    public void setSituacionrevistas(Set situacionrevistas) {
        this.situacionrevistas = situacionrevistas;
    }
    public Set getHoradesignadas() {
        return this.horadesignadas;
    }
    
    public void setHoradesignadas(Set horadesignadas) {
        this.horadesignadas = horadesignadas;
    }




}


